name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: ORT-DevOps-2023S2G1/workflows-repository/.github/workflows/main.yml@v1

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: ORT-DevOps-2023S2G1/workflows-repository/.github/workflows/main.yml@main
    with:
      config-path: .github/labeler.yml
    secrets: inherit
