name: Call a reusable workflow 

on:
  push:
    branches:
      - main
  
  # Allow workflow to be triggered manually
  workflow_dispatch:
permissions: write-all
jobs:
  job1:
    uses: ORT-DevOps-2023S2G1/workflows-repository/.github/workflows/main.yml@main
    secrets: inherit
  
 
