name: Call a reusable workflow and use its outputs

on:
  push:
    branches:
      - develop
  
  workflow_dispatch:
  

jobs:
  job1:
    uses: ORT-DevOps-2023S2G1/workflows-repository/.github/workflows/main.yml@main
