name: Call a reusable workflow and use its outputs

on:
  push:
    branches:
      - develop

jobs:
  job1:
    uses: ORT-DevOps-2023S2G1/workflows-repository/.github/workflows/main.yml@main

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
